apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: default
type: Opaque
data:
  postgres-db: c3RvcmU=
  postgres-user: c3RvcmU=
  postgres-password: NWVDcjN0
  jwt-secret-key: ZVhKQ1FtZFpiSFpLVVdWemJIcEdiR2RZT1UxR1dtTmpWRzlKTW1acVVrWnhkV0ZzY1hWbGNtTnZhWE5o
  exchange-api-key: ZjhhOGU4ZWIxYjk5MDlkODFlOTg4ZWM3

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: default
data:
  spring.profiles.active: "production"
  server.port: "8080"
  logging.level.store: "debug"
  exchange.api.base.url: "https://v6.exchangerate-api.com/v6"
  jwt.algorithm: "HS256"
  volume: "./volume"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: leosfreitas/auth:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: postgres-password
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: jwt-secret-key
        - name: EXCHANGE_API_KEY
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: exchange-api-key
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: spring.profiles.active
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: server.port
        - name: LOGGING_LEVEL_STORE
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: logging.level.store
        - name: EXCHANGE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: exchange.api.base.url
        - name: JWT_ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: jwt.algorithm
        - name: VOLUME
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: volume
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP