pipeline {
    agent any
    
    environment {
        DOCKER_REGISTRY = 'leosfreitas'
    }
    
    stages {
        stage('Checkout') {
            steps {
                echo 'Código baixado com sucesso!'
                bat 'dir'
                bat 'dir plataforma'
                bat 'dir plataforma\\api'
            }
        }
        
        stage('Verificar Estrutura') {
            steps {
                echo 'Verificando estrutura do projeto...'
                bat 'dir plataforma\\api /s /b | findstr pom.xml'
                bat 'dir plataforma\\api /s /b | findstr Dockerfile'
            }
        }
        
        stage('Verificar Java e Maven') {
            steps {
                bat 'java -version'
                bat 'mvn -version'
            }
        }
        
        stage('Build Services') {
            parallel {
                stage('Account Service') {
                    steps {
                        dir('plataforma/api/account-service') {
                            bat 'dir'
                            bat 'mvn clean package -DskipTests'
                        }
                    }
                }
                stage('Auth Service') {
                    steps {
                        dir('plataforma/api/auth-service') {
                            bat 'dir'
                            bat 'mvn clean package -DskipTests'
                        }
                    }
                }
                stage('Product Service') {
                    steps {
                        dir('plataforma/api/product-service') {
                            bat 'dir'
                            bat 'mvn clean package -DskipTests'
                        }
                    }
                }
                stage('Gateway Service') {
                    steps {
                        dir('plataforma/api/gateway-service') {
                            bat 'dir'
                            bat 'mvn clean package -DskipTests'
                        }
                    }
                }
            }
        }
        
        stage('Build Order Service') {
            steps {
                dir('plataforma/api/order-service') {
                    bat 'dir'
                    bat 'mvn clean package -DskipTests'
                }
            }
        }
    }
    
    post {
        success {
            echo 'Pipeline executado com sucesso!'
        }
        failure {
            echo 'Pipeline falhou, verificando logs...'
        }
        always {
            echo 'Processo finalizado'
        }
    }
}