
# --- dados básicos do site ---
site_name: Plataforma – APIs
site_description: Documentação mínima para teste
site_author: Seu Nome

# --- tema ---
theme:
  name: material
  language: pt

# --- extensões de markdown ---
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji

# --- navegação ---
nav:
  - Início: index.md
  - Individual:
      - Exchange API: exchange.md
      - Product API: product.md
      - Order API: order.md
      - Bottleneck: bottlenecks.md
      - Jenkins: jenkins.md
      - Minikubes: minicubes.md
  - Projetos:
      - Configuração do AWS: configAWS.md
      - Configuração do EKS: configEKS.md
      - Testes de Carga: testedecarga.md
      - CI/CD: cicd.md
      - Custos: custos.md
      - PaaS: paas.md
      - Vídeo: video.md
