server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:

        # - id: google
        #   uri: https://www.google.com
        #   predicates:
        #     - Path=/google/**

        - id: account
          uri: http://account:8080
          predicates:
            - Path=/account/**

        - id: auth
          uri: http://auth:8080
          predicates:
            - Path=/auth/**

        # - id: exchange
        #   uri: http://exchange:80
        #   predicates:
        #     - Path=/exchange/**

logging:
  level:
    store: ${LOGGING_LEVEL_STORE:debug}
